# _    _                 _
#| |  | |               (_)
#| |__| | ___  _   _ ___ _ _ __   __ _
#|  __  |/ _ \| | | / __| | '_ \ / _` |
#| |  | | (_) | |_| \__ \ | | | | (_| |
#|_|  |_|\___/ \__,_|___/_|_| |_|\__, |
#                                 __/ |
#                                |___/
debug: false
default-theme: default
database:
  # For the file based database use "file", for the mongo database use "mongo"
  type: file
  #MongoDB configuration
  mongo-db:
    host: localhost
    port: 27017
    #Leave blank if no user information is needed
    username: ""
    password: ""
houses:
  # The amount of houses a player can have
  maximum-player-houses: 20
  # The maximum amount of players a house can hold (can be bypassed with "housing.bypass.guest-limit")
  maximum-house-guests: 150