# _    _                 _
#| |  | |               (_)
#| |__| | ___  _   _ ___ _ _ __   __ _
#|  __  |/ _ \| | | / __| | '_ \ / _` |
#| |  | | (_) | |_| \__ \ | | | | (_| |
#|_|  |_|\___/ \__,_|___/_|_| |_|\__, |
#                                 __/ |
#                                |___/
debug: false
database:
  # For the file based database use "file", for the mongo database use "mongo"
  type: file